name: Run Python Script Manually

on:
  workflow_dispatch:  # Chỉ chạy khi kích hoạt thủ công từ GitHub Actions

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          pip install --upgrade pip
          pip install numpy pandas scikit-learn xgboost underthesea jupyterlab notebook ipykernel papermill openpyxl underthesea

      - name: Run Python Script
        run: |
          python dlm_label.py

      - name: Commit and Push Output
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add .
          git commit -m "Auto-update after running Python script" || echo "No changes to commit"
          git push
